modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/TheTestMod/BetterCrates/issues"
[[mods]]
modId="bettercrates"
version="${file.jarVersion}"
displayName="Better Crates"
displayURL="https://minecraft.curseforge.com/projects/better-crates"
authors="TheTestMod, FTB_lag"
description='''
Better storage of your items
'''
